### ISSUE TITLE
Fix type errors in scripts/ to unblock strict tsc --noEmit

### ISSUE THREAD

**Issue by andy-blum** [the-log/backend#12]
After upgrading TypeScript to 5.7 and adding `skipLibCheck`, `npx tsc --noEmit` is clean across the main codebase and tests — except for three files in `scripts/`, which are temporarily excluded via `tsconfig.json` (`"exclude": ["scripts", "node_modules"]`).

These were pre-existing errors on TS 4.9 as well; they only became visible when we started running `tsc --noEmit` as part of the test suite setup.

### `scripts/contracts/index.ts:4`
```
error TS2307: Cannot find module './contracts' or its corresponding type declarations.
```
Likely a gitignored data file. Either commit a stub, add a declaration, or refactor to load the data at runtime.

### `scripts/free_agency/index.ts` (13 errors)
Implicit-\`any\` parameters in sort/filter callbacks at lines 11, 12, 24–27, 143, plus \`Property 'sort' does not exist on type 'readonly any[]'\` at line 143 — the \`bids\` variable comes back as a readonly array and needs to be copied before sorting.

### `scripts/offseason/index.ts:304`
```
error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ QB: number; RB: number; WR: number; TE: number; K: number; DL: number; LB: number; DB: number; }'.
```
Narrow the \`pos\` variable to the position keys, or add an index signature.

## Acceptance
- [ ] Remove \`"scripts"\` from the \`exclude\` array in \`tsconfig.json\`
- [ ] \`npx tsc --noEmit\` exits 0
- [ ] Scripts still run via \`npm run scrape\` / \`offseason\` / \`free-agency\` / \`import-contracts\`
